- name: 'install ansible requirements'
  ansible.builtin.apt:
    name:
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-cryptography
      - python3-requests
    state: present
    update_cache: yes

- name: ensure ansible user exists
  ansible.builtin.user:
    name: '{{ username }}'
    password: '{{ password }}'
    state: present

- name: 'allow ansible user execute sudo without password'
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^{{ username }}'
    line: '{{ username }}  ALL=(ALL:ALL) NOPASSWD: ALL'

- name: add ansible public key to authorized_keys
  ansible.posix.authorized_key:
    user: '{{ username }}'
    key: '{{ pubkey }}'
    state: present

- name: create ansible directories
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ username }}'
    group: '{{ username }}'
    state: directory
  loop:
    - '{{ fact_path }}'