- name: ensure droplet exists
  community.digitalocean.digital_ocean_droplet:
    state: present
    oauth_token: '{{ api_token }}'
    name: '{{ name }}'
    size: '{{ size }}'
    region: '{{ region }}'
    image: '{{ image }}'
    wait_timeout: '{{ wait_timeout }}'
  delegate_to: localhost