# Install docker and compose
- name: 'install docker-ce repository'
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: 'add docker apt key'
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: 'add docker apt repo'
  ansible.builtin.apt_repository:
    repo: 'deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present

- name: 'install docker'
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: 'install docker python modules'
  ansible.builtin.pip:
    name:
      - docker[tls]
    state: present

- name: 'add docker user'
  ansible.builtin.user:
    name: docker
    group: docker
    state: present

- name: install docker plugins
  community.docker.docker_plugin:
    plugin_name: '{{ item.value }}'
    state: enable
    alias: '{{ item.key }}'
  loop: '{{ plugins|dict2items }}'

- name: 'dump docker daemon.json'
  ansible.builtin.copy:
    content: '{{ config|to_json }}'
    dest: /etc/docker/daemon.json

- name: 'enable and start the docker service'
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: 'restart docker daemon'
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: 'install docker-compose'
  ansible.builtin.pip:
    name:
      - docker-compose
    state: present
