---

- hosts: dockerhosts
  roles:
    - role: docker
      vars:
        plugins:
          loki: grafana/loki-docker-driver:latest
        config:
          # log-driver: json
          log-driver: loki
          log-opts:
            loki-url: 'https://myapp:{{ vault_loki_password }}@loki.myapp.com/loki/api/v1/push'
            loki-batch-size: '400'
